version: '3.9'
services:
  mongo:
    image: mongo:6.0
    container_name: pos-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: pos-redis
    restart: always
    ports:
      - 6379:6379

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pos-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos-frontend
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app

volumes:
  mongo-data:
